version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tags
    ports:
      - '5432:5432'

  tags:
    image: ghcr.io/multicash/mcxtags:1.0.0-rc02
    command: "api:serve --network testnet --dbhost db:5432"
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  db-data:
