name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/android/.gradle/caches
            ${{ github.workspace }}/android/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock', '**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-gradle-
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Yarn Modules
        run: yarn
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Build with Gradle
        run: ./gradlew bundleRelease
        working-directory: ./android
      - name: Upload Release Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: ${{ github.workspace }}/android/app/build/outputs/bundle/release/app-release.aab

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Artifact
        uses: actions/download-artifact@v2
        with:
          name: android-release
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: ${{ github.workspace }}
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload Release to Android Developers Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_UPLOAD_SERVICE_ACCOUNT_JSON }}
          packageName: com.multicash
          releaseFiles: ${{ steps.sign.outputs.signedReleaseFile }}
          track: alpha
          inAppUpdatePriority: 2
      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.sign.outputs.signedReleaseFile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
