name: iOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Prepare JS Build
        run: yarn
      - name: Install Pods
        run: pod install
        working-directory: ios
#      - name: Xcode Build
#        run: |
#          xcodebuild \
#                  -workspace ios/MultiCash.xcworkspace \
#                  -scheme MultiCash \
#                  archive \
#                  -sdk iphoneos \
#                  -configuration Debug \
#                  -archivePath $PWD/MultiCash \
#                  CODE_SIGNING_ALLOWED=NO
