name: IOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: CocoaPods install
        run: |
          sudo gem install cocoapods
          cd ios/ 
          pod install
      - name: Xcodebuild Action
        uses: sersoft-gmbh/xcodebuild-action@v1.1
        with:
          project: ./ios/MultiCash.xcodeproj
          scheme: MultiCash
          destination: id=0D24478B-82CF-4448-A245-1F88C71C9927
          action: build
