name: 🛠 Tests Suite

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn Modules
        run: yarn
      - name: Lint Javascript
        run: yarn lint
      - name: Run Unit-tests
        run: yarn test
